### ISSUE TITLE
Error occurs very often

### ISSUE THREAD

**Issue by E85Addict** [Hiumee/service.discord.richpresence#21]
So I've always had an issue where the addon would randomly stop working, and usually i just restart kodi, but it seems to happen more often below I will attach the errors I get when it happens. 

```
2024-10-29 19:39:51.842 T:10900   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-10-29 19:39:52.227 T:6296    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 22] Invalid argument
                                                   Traceback (most recent call last):
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 312, in updatePresence
                                                       self.presence.set_activity(activity)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 135, in set_activity
                                                       return self.send(data)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 115, in send
                                                       self._write(data_bytes)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 167, in _write
                                                       self._f.flush()
                                                   OSError: [Errno 22] Invalid argument
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 336, in onPlayBackEnded
                                                       drp.updatePresence()
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 307, in updatePresence
                                                       self.updatePresence()
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 317, in updatePresence
                                                       self.presence.set_activity(activity)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 135, in set_activity
                                                       return self.send(data)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 115, in send
                                                       self._write(data_bytes)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 167, in _write
                                                       self._f.flush()
                                                   OSError: [Errno 22] Invalid argument
                                                   -->End of Python script error report<--
                                                   

```

```
2024-10-29 21:53:58.370 T:6296    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 22] Invalid argument
                                                   Traceback (most recent call last):
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 312, in updatePresence
                                                       self.presence.set_activity(activity)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 135, in set_activity
                                                       return self.send(data)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 115, in send
                                                       self._write(data_bytes)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 167, in _write
                                                       self._f.flush()
                                                   OSError: [Errno 22] Invalid argument
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 382, in <module>
                                                       drp.mainLoop()
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 223, in mainLoop
                                                       self.updatePresence()
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 317, in updatePresence
                                                       self.presence.set_activity(activity)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 135, in set_activity
                                                       return self.send(data)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 115, in send
                                                       self._write(data_bytes)
                                                     File "C:\Users\E85Addict\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 167, in _write
                                                       self._f.flush()
                                                   OSError: [Errno 22] Invalid argument
                                                   -->End of Python script error report<--
                                                   

```

Two different times in a session it had the issue, I just disabled and reenabled it in the settings to fix it inbetween.

**Comment by Ridoou** [comment]
Same issue for me

**Comment by E85Addict** [comment]
Haven't had this issue happen in a long time, discord must've changed something a while back that stopped this from happening.
