### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by t0mtee** [Hiumee/service.discord.richpresence#7]
`2021-07-01 19:36:50.266 T:24732 WARNING: Trying to add unsupported control type 1
2021-07-01 19:36:50.694 T:26096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 22] Invalid argument
                                            Traceback (most recent call last):
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 279, in onPlayBackPaused
                                                drp.updatePresence()
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 271, in updatePresence
                                                self.presence.set_activity(activity)
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 131, in set_activity
                                                return self.send(data)
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 110, in send
                                                self._write(header)
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 163, in _write
                                                self._f.flush()
                                            IOError: [Errno 22] Invalid argument
                                            -->End of Python script error report<--
2021-07-01 19:36:59.257 T:19508   ERROR: XFILE::CDirectory::GetDirectory - Error getting \
2021-07-01 19:37:08.743 T:20820   ERROR: Previous line repeats 2 times.
2021-07-01 19:37:08.743 T:20820  NOTICE: script.module.metadatautils --> Rate limiter active for themoviedb.org - delaying request with 5 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
2021-07-01 19:37:20.507 T:26096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 22] Invalid argument
                                            Traceback (most recent call last):
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 338, in <module>
                                                drp.mainLoop()
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 187, in mainLoop
                                                self.updatePresence()
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\default.py", line 271, in updatePresence
                                                self.presence.set_activity(activity)
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 131, in set_activity
                                                return self.send(data)
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 111, in send
                                                self._write(data_bytes)
                                              File "C:\Users\tomt0\AppData\Roaming\Kodi\addons\service.discord.richpresence\lib\discordpresence.py", line 163, in _write
                                                self._f.flush()
                                            IOError: [Errno 22] Invalid argument
                                            -->End of Python script error report<--`

**Comment by t0mtee** [comment]
This doesn't crash anything, it just randomly happens sometimes
